In [1]:
import numpy as np

In [21]:
# Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [69]:
# Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
# Convert a 1D array to a 2D array with 2 rows
arr=np.arange(10)
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [72]:
# Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[a<5 and a>10]
a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
# Create a null vector of size 10 but the fifth value which is 1.
a = np.full((5,5),'Null')
a[a[4]] = 1

IndexError: arrays used as indices must be of integer (or boolean) type

In [35]:
# Create a vector with values ranging from 10 to 49.
vector = np.arange(10,50)

vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [63]:
# Create a 10x10 array with random values and find the minimum and maximum values.
vector = np.random.randint(10,100,(10,10))
print(vector)
print("max value",vector.max())
print("max value",vector.min())

[[25 70 68 26 19 96 12 37 14 41]
 [11 23 93 14 69 77 17 59 57 75]
 [71 24 65 81 90 12 29 73 63 37]
 [66 40 58 57 49 48 54 28 74 66]
 [44 63 84 27 82 23 40 27 63 78]
 [60 93 63 88 10 23 67 86 13 80]
 [13 94 89 20 97 70 13 58 62 53]
 [46 15 81 48 96 52 94 86 43 68]
 [52 32 10 65 29 63 78 72 60 78]
 [45 33 19 58 31 35 64 16 47 68]]
max value 97
max value 10


In [41]:
# Create a 3*3 matrix and print it's transpose matrix
matrix = np.array([[1,3,4,5],
                  [3,54,6,7],
                  [23,56,7,8]])
matrix.T

array([[ 1,  3, 23],
       [ 3, 54, 56],
       [ 4,  6,  7],
       [ 5,  7,  8]])

In [42]:
# Create two arrays of 2-D and find dot product of it.
a = np.array([[3,2],
               [2,4]])
b = np.array([[3,1],
               [1,4]]) 
np.dot(a,b)

array([[11, 11],
       [10, 18]])

In [54]:
# Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print("max from each row",a.max(axis =1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
max from each row [9 8 6 3 9]


In [43]:
# Select 3rd & 5th row and 3rd & 4th columns
data = np.random.randint(10,100,(5,4))
data

array([[79, 63, 29, 62],
       [34, 28, 94, 45],
       [78, 96, 29, 53],
       [47, 97, 40, 24],
       [58, 13, 86, 43]])

In [44]:
data[[2,4],2:4]

array([[29, 53],
       [86, 43]])

In [16]:
# Convert below matrix into vector
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [58]:
# The product of two inverse matrix is identical matrix,prove
# create a square matrix
m = np.array([[2,3],
              [2,4]])
print(m.T)
print(np.dot(t))

[[2 2]
 [3 4]]


NameError: name 't' is not defined

In [46]:
# Create a matrix from a uniform distribution over [0, 1)
data = np.random.randn(5,4)
data

array([[ 0.17086301, -0.59970748,  2.65975058,  0.99683627],
       [-0.23198063, -0.51772213,  1.43018797,  0.94971126],
       [ 0.65692046,  0.22203428,  0.59829059, -1.75037385],
       [ 0.13330585, -1.31520994, -0.9374954 ,  0.38421144],
       [-0.66167997,  2.58785597, -1.08310212, -2.06634065]])